// <auto-generated />
using System;
using HoraCerta.Infaestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoraCerta.Infaestrutura.Persistencia.Migrations
{
    [DbContext(typeof(HoraCertaDbContext))]
    [Migration("20260517145757_Onda2LembretesAuthAvaliacao")]
    partial class Onda2LembretesAuthAvaliacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.ClienteRegistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.CredencialProprietarioRegistro", b =>
                {
                    b.Property<string>("ProprietarioId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProprietarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("credenciais_proprietario", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.LembreteRegistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgendamentoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnviarEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SlotInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("Status", "EnviarEm");

                    b.ToTable("lembretes", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.ProprietarioRegistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("proprietarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
