// <auto-generated />
using System;
using HoraCerta.Infaestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoraCerta.Infaestrutura.Persistencia.Migrations
{
    [DbContext(typeof(HoraCertaDbContext))]
    [Migration("20260528005000_Onda3WhatsAppOutbox")]
    partial class Onda3WhatsAppOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.ClienteRegistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.CredencialProprietarioRegistro", b =>
                {
                    b.Property<string>("ProprietarioId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProprietarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("credenciais_proprietario", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.LembreteRegistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgendamentoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnviarEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SlotInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("Status", "EnviarEm");

                    b.ToTable("lembretes", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.MensagemOutboxRegistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProximaTentativaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneDestino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tentativas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey");

                    b.HasIndex("Status", "ProximaTentativaEm");

                    b.ToTable("mensagens_outbox", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.ProprietarioRegistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("proprietarios", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.SessaoConversaRegistro", b =>
                {
                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietarioId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePendente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Passo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedimentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotHorarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Telefone", "ProprietarioId");

                    b.ToTable("sessoes_conversa", (string)null);
                });

            modelBuilder.Entity("HoraCerta.Infaestrutura.Persistencia.Registros.WebhookTwilioProcessadoRegistro", b =>
                {
                    b.Property<string>("MessageSid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageSid");

                    b.ToTable("webhooks_twilio_processados", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
